/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appclientes;

/**
 *
 * @author Gabriel
 */
public class VentanaClientes extends javax.swing.JFrame {

    int cantidad = 0;
    int iterador = 0;
    int cliente = 1;
    int [] edades = null;
    String [] nombres = null;    
    
    public VentanaClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoNombre = new javax.swing.JTextField();
        campoEdad = new javax.swing.JTextField();
        cNombre = new javax.swing.JLabel();
        cEdad = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        botonOK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cNombre.setText("Nombre");

        cEdad.setText("Edad");

        titulo.setText("Ingrese cliente 1");

        botonOK.setText("ACEPTAR");
        botonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOKActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(campoNombre)
                    .addComponent(campoEdad, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cNombre)
                            .addComponent(cEdad)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(botonOK)))
                        .addGap(0, 271, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(cEdad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonOK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOKActionPerformed
        nombres[iterador] = campoNombre.getText();
        edades[iterador] = Integer.parseInt(campoEdad.getText());
        iterador++;
        cliente++;
        titulo.setText("Ingrese cliente "+cliente);
        campoNombre.setText("");
        campoEdad.setText("");     
        
        if (iterador == cantidad) {
            cliente=1;
            titulo.setText("Ingrese cliente "+cliente);
            campoNombre.setText("");
            campoEdad.setText("");
            mayoresEdad(edades);
            menoresEdad(edades);
            promedioEdades(edades);
            edadMaxima(edades, nombres);
            edadMinima(edades, nombres);
            iterador = 0;
        }
        

    }//GEN-LAST:event_botonOKActionPerformed

    public void mayoresEdad(int [] lista) {
        int i = 0;
        int cant = 0;
        while (i < lista.length) {
            if (lista[i] >= 18) {
                cant++;
            }
            i++;
        }
        String salida = "Hay "+cant+" clientes mayores de edad.\n";
        this.jTextArea1.append(salida);
    }
    
    public void menoresEdad(int [] lista) {
        int i = 0;
        int cant = 0;
        while (i < lista.length) {
            if (lista[i] < 18) {
                cant++;
            }
            i++;
        }
        String salida = "Hay "+cant+" clientes menores de edad.\n";
        this.jTextArea1.append(salida);
    }

    public void promedioEdades(int [] lista) {
        int i = 0;
        int suma = 0;
        int promedio = 0;
        
        while (i < lista.length) {
            suma = suma + lista[i];
            i++;
        }
        
        promedio = suma / lista.length;
        
        String salida = "El promedio de edad es "+promedio+".\n";
        this.jTextArea1.append(salida);
    }

    public void edadMaxima(int [] lista, String [] nombres) {
        int i = 0;
        int max = 0;
        String salida = "";
        
        while (i < lista.length) {
            if (lista[i] > max) {
                max = lista[i];
            }
            i++;
        }
        
        i = 0;
        while (i < lista.length) {
            if (lista[i] == max) {
                salida = "La edad mas alta es de "+nombres[i]+" con "+max+"años.\n";
                this.jTextArea1.append(salida);
            }
            i++;
        } 
    }

    public void edadMinima(int [] lista, String [] nombres) {
        int i = 0;
        int min = 9999;
        String salida = "";
        
        while (i < lista.length) {
            if (lista[i] < min) {
                min = lista[i];
            }
            i++;
        }
        
        i = 0;
        while (i < lista.length) {
            if (lista[i] == min) {
                salida = "La edad mas baja es de "+nombres[i]+" con "+min+"años.\n";
                this.jTextArea1.append(salida);
            }
            i++;
        } 
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaClientes().setVisible(true);
            }
        });
    }
    
    public void setCantidad(int cant) {
        cantidad = cant;
    }

    public void setVectores(int cant) {
        edades = new int [cant];
        nombres = new String [cant];
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonOK;
    private javax.swing.JLabel cEdad;
    private javax.swing.JLabel cNombre;
    private javax.swing.JTextField campoEdad;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}